FROM python:3.11-slim
WORKDIR /code
COPY requirements-core.txt .
RUN pip install --no-cache-dir -r requirements-core.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8005"]
