"""add_energy_level

Revision ID: 237459baee67
Revises: 537f3ea3e513
Create Date: 2026-02-15 22:40:43.982505
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '237459baee67'
down_revision = '537f3ea3e513'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('energy_level', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'energy_level')
    # ### end Alembic commands ###