"""add subtasks and duration

Revision ID: 537f3ea3e513
Revises: 20240207_0001
Create Date: 2026-02-15 20:59:07.830251
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '537f3ea3e513'
down_revision = '20240207_0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('labels', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'duration_minutes')
    # ### end Alembic commands ###