"""create_projects_table

Revision ID: 8eb381972261
Revises: 537f39d2c4e4_manual
Create Date: 2026-02-16 11:15:28.031461
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8eb381972261'
down_revision = '537f39d2c4e4_manual'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=16), server_default='🚀', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_index('automation_runs_auto_idx', table_name='automation_runs')
    op.create_index(op.f('ix_automation_runs_automation_id'), 'automation_runs', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_id'), 'automation_runs', ['id'], unique=False)
    op.drop_index('automations_user_idx', table_name='automations')
    op.create_index(op.f('ix_automations_id'), 'automations', ['id'], unique=False)
    op.create_index(op.f('ix_automations_user_id'), 'automations', ['user_id'], unique=False)
    op.drop_index('external_events_task_idx', table_name='external_events')
    op.create_index(op.f('ix_external_events_id'), 'external_events', ['id'], unique=False)
    op.create_index(op.f('ix_external_events_task_id'), 'external_events', ['task_id'], unique=False)
    op.drop_index('integration_events_integration_idx', table_name='integration_events')
    op.create_index(op.f('ix_integration_events_id'), 'integration_events', ['id'], unique=False)
    op.create_index(op.f('ix_integration_events_integration_id'), 'integration_events', ['integration_id'], unique=False)
    op.drop_index('integrations_provider_idx', table_name='integrations')
    op.drop_index('integrations_user_idx', table_name='integrations')
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.drop_index('idx_intents_name', table_name='intents')
    op.drop_constraint('uq_intents_name', 'intents', type_='unique')
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    op.create_index(op.f('ix_intents_name'), 'intents', ['name'], unique=True)
    op.drop_index('recurrence_rules_template_idx', table_name='recurrence_rules')
    op.drop_index('recurrence_rules_user_idx', table_name='recurrence_rules')
    op.create_index(op.f('ix_recurrence_rules_id'), 'recurrence_rules', ['id'], unique=False)
    op.create_index(op.f('ix_recurrence_rules_template_id'), 'recurrence_rules', ['template_id'], unique=False)
    op.create_index(op.f('ix_recurrence_rules_user_id'), 'recurrence_rules', ['user_id'], unique=False)
    op.drop_index('task_templates_user_idx', table_name='task_templates')
    op.create_index(op.f('ix_task_templates_id'), 'task_templates', ['id'], unique=False)
    op.create_index(op.f('ix_task_templates_intent_id'), 'task_templates', ['intent_id'], unique=False)
    op.create_index(op.f('ix_task_templates_user_id'), 'task_templates', ['user_id'], unique=False)
    op.drop_index('tasks_intent_idx', table_name='tasks')
    op.drop_index('tasks_user_due_idx', table_name='tasks')
    op.drop_index('tasks_user_status_idx', table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_intent_id'), 'tasks', ['intent_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_intent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index('tasks_user_status_idx', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index('tasks_user_due_idx', 'tasks', ['user_id', 'due_at'], unique=False)
    op.create_index('tasks_intent_idx', 'tasks', ['intent_id'], unique=False)
    op.drop_index(op.f('ix_task_templates_user_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_intent_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_id'), table_name='task_templates')
    op.create_index('task_templates_user_idx', 'task_templates', ['user_id'], unique=False)
    op.drop_index(op.f('ix_recurrence_rules_user_id'), table_name='recurrence_rules')
    op.drop_index(op.f('ix_recurrence_rules_template_id'), table_name='recurrence_rules')
    op.drop_index(op.f('ix_recurrence_rules_id'), table_name='recurrence_rules')
    op.create_index('recurrence_rules_user_idx', 'recurrence_rules', ['user_id'], unique=False)
    op.create_index('recurrence_rules_template_idx', 'recurrence_rules', ['template_id'], unique=False)
    op.drop_index(op.f('ix_intents_name'), table_name='intents')
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.create_unique_constraint('uq_intents_name', 'intents', ['name'])
    op.create_index('idx_intents_name', 'intents', ['name'], unique=False)
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.create_index('integrations_user_idx', 'integrations', ['user_id'], unique=False)
    op.create_index('integrations_provider_idx', 'integrations', ['provider'], unique=False)
    op.drop_index(op.f('ix_integration_events_integration_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_id'), table_name='integration_events')
    op.create_index('integration_events_integration_idx', 'integration_events', ['integration_id'], unique=False)
    op.drop_index(op.f('ix_external_events_task_id'), table_name='external_events')
    op.drop_index(op.f('ix_external_events_id'), table_name='external_events')
    op.create_index('external_events_task_idx', 'external_events', ['task_id'], unique=False)
    op.drop_index(op.f('ix_automations_user_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_id'), table_name='automations')
    op.create_index('automations_user_idx', 'automations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_automation_runs_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_id'), table_name='automation_runs')
    op.create_index('automation_runs_auto_idx', 'automation_runs', ['automation_id'], unique=False)
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###