"""add_user_personalization_columns

Revision ID: 983eaeef9a6a
Revises: a216e69687dc
Create Date: 2026-02-16 11:35:56.809801
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '983eaeef9a6a'
down_revision = 'a216e69687dc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preference', sa.String(length=16), server_default='light', nullable=False))
    op.add_column('users', sa.Column('accent_color', sa.String(length=7), server_default='#9333ea', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accent_color')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###