"""add_embedding_columns

Revision ID: a216e69687dc
Revises: 8eb381972261
Create Date: 2026-02-16 11:24:06.089403
"""

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'a216e69687dc'
down_revision = '8eb381972261'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    op.add_column('tasks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'embedding')
    op.drop_column('projects', 'embedding')
    # ### end Alembic commands ###